spring.application.name=estacionamento
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/estacionamento}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:estacionamento}
spring.datasource.password=${DATABASE_PASSWORD:estacionamento}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
