CREATE TABLE IF NOT EXISTS veiculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_discriminador VARCHAR(31) NOT NULL,
    placa VARCHAR(10) NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    cor VARCHAR(255) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    CONSTRAINT uk_veiculo_placa UNIQUE (placa),
    CONSTRAINT ck_veiculo_tipo CHECK (tipo IN ('CARRO', 'MOTO', 'CAMINHONETE')),
    CONSTRAINT ck_veiculo_tipo_discriminador CHECK (tipo_discriminador IN ('CARRO', 'MOTO', 'CAMINHONETE'))
);

CREATE TABLE IF NOT EXISTS vaga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(255) NOT NULL,
    ocupada BOOLEAN NOT NULL,
    CONSTRAINT uk_vaga_numero UNIQUE (numero)
);

CREATE TABLE IF NOT EXISTS movimentacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id BIGINT NOT NULL,
    vaga_id BIGINT NOT NULL,
    data_entrada TIMESTAMP NOT NULL,
    data_saida TIMESTAMP,
    valor_pago NUMERIC(19, 2),
    CONSTRAINT fk_movimentacao_veiculo
        FOREIGN KEY (veiculo_id)
        REFERENCES veiculo (id),
    CONSTRAINT fk_movimentacao_vaga
        FOREIGN KEY (vaga_id)
        REFERENCES vaga (id),
    CONSTRAINT ck_movimentacao_periodo
        CHECK (data_saida IS NULL OR data_saida >= data_entrada),
    CONSTRAINT ck_movimentacao_valor_pago
        CHECK (valor_pago IS NULL OR valor_pago >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_movimentacao_veiculo_aberta
    ON movimentacao (veiculo_id)
    WHERE data_saida IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_movimentacao_vaga_aberta
    ON movimentacao (vaga_id)
    WHERE data_saida IS NULL;

CREATE INDEX IF NOT EXISTS ix_movimentacao_data_entrada
    ON movimentacao (data_entrada);

CREATE INDEX IF NOT EXISTS ix_movimentacao_data_saida
    ON movimentacao (data_saida);
